[package]
name = "grid"
version = "0.1.0"
authors = ["Scott Vickers <scott.w.vickers@gmail.com>"]
edition = "2018"

[dependencies]
gust = { path = "../gust", version = "0.1.0" }
line-rs = { path = "../line-rs", version = "0.1.0" }
rand = "0.6.0"
image = "0.21.1"
